#setwd("C:/Users/USER/R studio")
#install.packages("tidyverse")
#install.packages("sf")
#install.packages("ggmap")
#install.packages("tmap")
#install.packages("rsdmx")
#install.packages("knitr")
#install.packages("ggspatial")
#install.packages("curl")
#install.packages("rnaturalearth")
#install.packages("lubridate")
#install.packages("basemaps")
#install.packages("gstat")
#install.packages("scico")
#install.packages("remotes")
#remotes::install_github("tylermorganwall/rayshader") 
#remotes::install_github("dmurdoch/rgl")
#install.packages("magick") 
#install.packages('dygraphs')
#install.packages("rmarkdown")
#install.packages("COVID19")
#install.packages("flexdashboard")
library(tidyverse) #  collection of R packages designed for data science
library(sf) # spatial data as simple features
library(maptools) # spatial data
library(spatstat) # spatial statistics
library(rgeos)
library(lubridate)
library(RColorBrewer)
library(gstat)
library(tmap) # thematic maps
library(ggthemes) # additional predefined themes for ggplot2 plots
library(RColorBrewer)
library(rnaturalearth)
library(GISTools)
library(rsdmx)
library(dplyr)
library(knitr)
library(basemaps)
library(ggspatial)
library(stringr)
library(ggmap)
library(readxl)
library(curl) # library to download data from web
library(raster)
library(maptools)
library(rgeos)
library(scico)
library(XML)
library(data.table)
library(lubridate)
library(GISTools)
library(gplots)
library(magick)
library(raster)
library(rayrender)
library(remotes)
library(rayshader)
library(av)
library(plotly)
library(leaflet)
library(gganimate)
library(dygraphs)
library(xts)
library(rmarkdown)
library(leaflet)
library(RColorBrewer)

